# Generated by Django 3.1.1 on 2020-09-08 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=32)),
                ('first_emoji', models.JSONField(default=list, verbose_name=models.CharField(blank=True, max_length=8))),
                ('last_emoji', models.JSONField(default=list, verbose_name=models.CharField(blank=True, max_length=8))),
                ('first_user_id', models.JSONField(default=list, verbose_name=models.IntegerField(null=True))),
                ('last_user_id', models.JSONField(default=list, verbose_name=models.IntegerField(null=True))),
            ],
        ),
        migrations.CreateModel(
            name='GameCompletion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=32)),
                ('seed', models.IntegerField()),
                ('first', models.BooleanField()),
                ('emoji', models.CharField(max_length=8)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
