# Generated by Django 3.1.1 on 2020-09-10 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=32)),
                ('first_flag', models.JSONField(default=list, verbose_name=models.CharField(blank=True, max_length=8))),
                ('last_flag', models.JSONField(default=list, verbose_name=models.CharField(blank=True, max_length=8))),
                ('first_user_id', models.JSONField(default=list, verbose_name=models.IntegerField(null=True))),
                ('last_user_id', models.JSONField(default=list, verbose_name=models.IntegerField(null=True))),
            ],
        ),
        migrations.CreateModel(
            name='GameCompletion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=32)),
                ('seed', models.IntegerField()),
                ('first', models.BooleanField(default=False)),
                ('flag', models.CharField(max_length=8)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('actions', models.JSONField(default=dict)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions.session')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
